#!/bin/bash -x

tmux has-session -t ms-demo > /dev/null 2>&1 
if [ $? != 0 ]; then

	echo "starting new session"
	tmux new-session -s ms-demo -n Redis -d

	tmux send-keys -t :"Redis" "docker run --rm -p 6379:6379 redislabs/redismod:latest" Enter

	tmux new-window -d -t "=ms-demo" -n "Kong"
	tmux send-keys -t :"Kong" "docker run --rm --name kong -e KONG_DATABASE=off -e KONG_PROXY_ACCESS_LOG=/dev/stdout -e KONG_ADMIN_ACCESS_LOG=/dev/stdout -e KONG_PROXY_ERROR_LOG=/dev/stderr -e KONG_ADMIN_ERROR_LOG=/dev/stderr -e \"KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl\" -p 8000:8000 -p 8443:8443 -p 8001:8001 -p 8444:8444 kong" Enter

	tmux new-window -d -t "=ms-demo" -n "Catalog"
	tmux send-keys -t :"Catalog" "cd catalog && source catalog-venv/bin/activate && python3 app.py" Enter

	tmux new-window -d -t "=ms-demo" -n "Login"
	tmux send-keys -t :"Login" "cd login && source login-venv/bin/activate && python3 app.py" Enter

	tmux new-window -d -t "=ms-demo" -n "Logs"
	tmux send-keys -t :"Logs" "cd logs && source logs-venv/bin/activate && python3 app.py" Enter

	tmux new-window -d -t "=ms-demo" -n "Cart"
	tmux send-keys -t :"Cart" "cd cart && source cart-venv/bin/activate && python3 app.py" Enter

fi

tmux attach -t ms-demo
